### ISSUE TITLE
wrap words around images, and ensure images are not stretched

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corperate-communications#102]
![image](https://user-images.githubusercontent.com/5694308/81803473-eecc4a00-9541-11ea-9170-0d43f67952ab.png)

**Comment by mort3za** [comment]
@ctyar I want you to do some math on image width of articles, we don't need actual image width in email template.

image width in wide articles (two column): 200
image width in wide articles (three column): 280
image width in middle articles (two column): 185
image width in middle articles (three column): 163

NOTE: height should be relative to width
NOTE: if actual image width was less than top values, use minimum width
NOTE: we use 2x images (for retina displays), so if actual image width was 400px, we show it in 200px area

Examples:  

### wide article / two column template

actualHeight = 400
actualWidth = 600
maximumWidth = 200
retinaRatio = 2
calculated image width in email template => min( (actualWidth / retinaRatio), maximumWidth) => 200
calculated image height => (calculatedWidth / actualWidth) * actualHeight => 133.33

final article object would be: 
{
headline: ...,
description: (full description),
description_part1: (part 1 of description),
description_part2: (part 2 of description),
image: {
    wrapperWidth: 200 (same value of "image width in wide articles (two column)" without change),
    url: ...,
    width: 200 (calculated width),
    height: 133.33
  }
}

**Comment by ctyar** [comment]
Implemented in the API

**Comment by mort3za** [comment]
**UPDATE:** 
> maximum image width in middle articles (three column): 163

new value: 161

**Comment by ctyar** [comment]
Done
