### ISSUE TITLE
community category shows priority icon on email

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corperate-communications#105]
![image](https://user-images.githubusercontent.com/5694308/82276312-1f333e80-99af-11ea-8cb1-97f408a4b885.png)

**Comment by mort3za** [comment]
Category image is coming from API, you can update it in database. `category.image`.

**Comment by paulchrisluke** [comment]
I have it set correctly I believe @mort3za :

![image](https://user-images.githubusercontent.com/5694308/82311069-69d4ab00-99ef-11ea-8b92-c392dc61e974.png)

![image](https://user-images.githubusercontent.com/5694308/82311176-8d97f100-99ef-11ea-8bdf-7b79576856da.png)


@ctyar ?

**Comment by mort3za** [comment]
Okay, if you try sending another template it should be correct. We had a template issue too that is fixed now. (but creating a new community article is disabled in CMS)
