### ISSUE TITLE
One Team Component

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corperate-communications#13]
![image](https://user-images.githubusercontent.com/5694308/77982008-74e75500-7335-11ea-90f3-0eedf3239c48.png)
This component is specific to One Team content in Volkswagen's Responsive Email Template. The One Team Component has 3 different styles that adjust responsively 
![image](https://user-images.githubusercontent.com/5694308/77982035-82044400-7335-11ea-80b3-97e31ce7b50c.png)
![image](https://user-images.githubusercontent.com/5694308/77982045-89c3e880-7335-11ea-8155-8f866594c864.png)

##  One Team

The "One Team" Sections have different parts: 
1. Background Card
2. Top One Team Logo 
3. Title
4. Body Text 

**Before setting this card up, the color "One Team" needs to be added into local color styles #4  #D9EFFF**

### Card 
![image](https://user-images.githubusercontent.com/5694308/77982834-76198180-7337-11ea-8d2b-db0c128159f0.png)
The card is the background of the component. It has a 16 pixel margin around the text box area from the left/right/bottom 

The card includes different rounded corner radius: 
![image](https://user-images.githubusercontent.com/5694308/77983019-0b1c7a80-7338-11ea-847b-c6286e7e84e3.png)
Top corners: 3 pixel
![image](https://user-images.githubusercontent.com/5694308/77983027-14a5e280-7338-11ea-851c-65272d14b3b9.png)
Bottom corners: 15 pixels 

Background Color: One Team 
Shadow: Print Shadow

### Top One Team Logo
![image](https://user-images.githubusercontent.com/5694308/77982978-e7593480-7337-11ea-82a4-c80560d63378.png)

The logo includes 3 layers, in order of top to bottom, layered centered within each other: 
1. logo
2. circle 
3. Circle Cutout

1. Logo
![image](https://user-images.githubusercontent.com/5694308/77983621-a95d1000-7339-11ea-8d3e-205fc91708dd.png)
The one team logo is 76 pixel by 76 pixels, colored to be the primary color 

2. circle 
![image](https://user-images.githubusercontent.com/5694308/77983771-05279900-733a-11ea-8c4a-3cdb959a01f3.png)
The circle is 87x87, 4 pixel stroke 
Color: Primary Color

3. Circle Cutout 
![image](https://user-images.githubusercontent.com/5694308/77983821-26888500-733a-11ea-85c5-ffa7997bc2d9.png)
![image](https://user-images.githubusercontent.com/5694308/77985262-2ee2bf00-733e-11ea-8b6b-7cd58aa351e6.png)
The circle is 98x98 pixels, centered on the card horizontally, and 3/4th on the card background, making a cut-out like effect. 

### Title 
![image](https://user-images.githubusercontent.com/5694308/77985469-c9430280-733e-11ea-83ee-f53d2c7fb9c9.png)
The title of the article 
For print/desktop - 
font: print title

For tablet/mobile -
Font: H2

### Body Text 
![image](https://user-images.githubusercontent.com/5694308/77985482-d06a1080-733e-11ea-9b10-cf90eb63cc61.png)
For print/desktop - 
Font: Print Body 
Emphasis Font: Print Body Empahsis 

For tablet/mobile
Font: Body 1 
Emphasis Font: Body 1 Empahsis 

### Design File
The specs for each individual style can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

**Comment by mort3za** [comment]
I need these parts as separate images.

![image](https://user-images.githubusercontent.com/510242/82028524-007d3100-96ab-11ea-83de-a703014bb8fd.png)

Please consider that our shadows are 2px solid border, so it should match with shadow of other articles.  
Preferably attach images with and without shadow.
@paulchrisluke

**Comment by paulchrisluke** [comment]
[Corners.zip](https://github.com/whynotearth/Volkswagen-email-corperate-communications/files/4634531/Corners.zip)

All corners with and without shadows in separate folders

**Comment by mort3za** [comment]
Sorry could you send 2x images? without shadow only

**Comment by paulchrisluke** [comment]
@mort3za 
2x without shadows 
[Without Shadow.zip](https://github.com/whynotearth/Volkswagen-email-corperate-communications/files/4635024/Without.Shadow.zip)

**Comment by mort3za** [comment]
[dist.zip](https://github.com/whynotearth/Volkswagen-email-corperate-communications/files/4637923/dist.zip)

@ctyar one-team component added.

**Comment by ctyar** [comment]
@mort3za Updated
