### ISSUE TITLE
Stepper Top Navigation

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corperate-communications#25]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

For the design and the flow, go to the "Prototype" page. For the smart suggestion warnings/article prioritization/layout, see "Logic Map" page.

This milestone is due **April 6th, 2020**

This is the component for stepper top navigation for Volkswagen's email CMS system
![image](https://user-images.githubusercontent.com/5694308/78467493-9c745e00-7737-11ea-8523-6653ec2e887c.png)

<hr>

# Content 
The title, text action, and step progress will be stated in linked issues where available 
Title: {{page title}}
Text action: {{text action}}
Steps: {{x}} of {{x}}

# Assets
<img width="24" alt="back" src="https://user-images.githubusercontent.com/5694308/78467583-57046080-7738-11ea-803e-0ea5c81bd0fe.png">

# Alignment 
**Title:** 
margin top-bottom: 16 px 
![image](https://user-images.githubusercontent.com/5694308/78467684-57512b80-7739-11ea-97f6-a6ebcad41116.png)

**Icon:** 
margin top-bottom: 16 px 
margin left: 16 px 
![image](https://user-images.githubusercontent.com/5694308/78468447-74d6c300-7742-11ea-8856-1bbd07826743.png)

![image](https://user-images.githubusercontent.com/5694308/78468441-69839780-7742-11ea-934d-8f5493f22975.png)

**Text Action:**
margin top-bottom: 16 px 
margin right; 16 px 
![image](https://user-images.githubusercontent.com/5694308/78468477-b1a2ba00-7742-11ea-8b2c-59304d747bd7.png)

**Stepper Dots:** 
8 pixel dots 
margin top-bottom: 16 px 
![image](https://user-images.githubusercontent.com/5694308/78468431-4fe25000-7742-11ea-8b16-d751e4f71240.png)
gutter-margin: 8 px 
![image](https://user-images.githubusercontent.com/5694308/78468488-c8491100-7742-11ea-96be-a42ff05467e2.png)

# Text Styles
Title:  
```
/* H2 */

font-family: Work Sans;
font-style: normal;
font-weight: 600;
font-size: 22px;
line-height: 26px;
```

Text Action: 
```
/* H3 */

font-family: Work Sans;
font-style: normal;
font-weight: 500;
font-size: 20px;
line-height: 25px;
/* or 125% */
```

# Colors
Background: Background (#FFFFFF)
Title: Primary (#011D51)
Text: Secondary (#03B3F9)
Active stepper dot: Secondary (#03B3F9)
Inactive stepper dot: On Background, Disabled (#000000, 38%)

**Comment by paulchrisluke** [comment]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

For the design and the flow, go to the "Prototype" page. For the smart suggestion warnings/article prioritization/layout, see "Logic Map" page.

# Top Stepper Navigation
 
This is a brand new stepper navigation 
https://github.com/whynotearth/foodouken.com/issues/97 We are using a stepper navigation identical to this issue, except this is for volkswagen branding. 

![image](https://user-images.githubusercontent.com/5694308/79103747-5eaab180-7d97-11ea-979c-650cf8e4e328.png)

# Content 
Title: {{ Current Step }} 
Subtitle : {{ Next Step }} 
Steps: {{ x of x steps }} 
Button 1: Back
Button 2: {{ Next Step }} 

# Text Style
Title: 
```
/* Desktop H2 */

font-family: Work Sans;
font-style: normal;
font-weight: 600;
font-size: 44px;
line-height: 40px;
/* identical to box height, or 91% */
```

Steps, Subtitle: 
```
/* Desktop Body */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 32px;
line-height: 38px;
```

Buttons: 
```
/* Desktop Body Emphasis */

font-family: Work Sans;
font-style: normal;
font-weight: 600;
font-size: 32px;
line-height: 20px;
/* identical to box height, or 62% */
```

# Color 
Background: Surface (#FFFFFF)
Title: Primary (#011D51)
Subtitle: Primary (#011D51)
Unfilled Stepper Circle: On Surface Divider (#000000, 12%)
Filled Stepper Circle: Secondary (#03B3F9)
Stepper Circle Text: On Surface High Emphasis (#000000, 84%)
Button Text 1: Error (#FF5959)
Button Background 1: Surface (#FFFFFF) 
Button Text 2: On Primary High Emphasis (#FFFFFF, 84%) 
Button Background 2: Primary (#011D51)

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/79293097-f5dd4980-7efc-11ea-9eb7-94aa76446da7.png)
This is the design on the left, the live site on the right 

# Stepper 
![image](https://user-images.githubusercontent.com/5694308/79293754-aa2b9f80-7efe-11ea-8a2e-f00155a2f516.png)
Stepper should be the size of the text margin and lines up with the content, bottom bar arrow icon 


![image](https://user-images.githubusercontent.com/5694308/79293651-794b6a80-7efe-11ea-836f-1fc94bef1cfb.png)
the ends of the blue lines need to be rounded 

# Text Style 
![image](https://user-images.githubusercontent.com/5694308/79294221-d3006480-7eff-11ea-88e7-504712cbc9ea.png)
![image](https://user-images.githubusercontent.com/5694308/79294286-ee6b6f80-7eff-11ea-8cde-705f5bd1ff5f.png)
Current text style does not match design
Our text style is [Work Sans](https://fonts.google.com/specimen/Work+Sans)

![image](https://user-images.githubusercontent.com/5694308/79292368-2623e880-7efb-11ea-9268-fe5e280c7d0b.png)
The title for each step should be semi-bolded 

Title Font Style:
```
/* Mobile H2 */

font-family: Work Sans;
font-style: normal;
font-weight: 600;
font-size: 22px;
line-height: 26px;
```
```
/* Desktop H2 */

font-family: Work Sans;
font-style: normal;
font-weight: 600;
font-size: 44px;
line-height: 40px;
/* identical to box height, or 91% */
```

# Desktop 
![image](https://user-images.githubusercontent.com/5694308/79293447-f6c2ab00-7efd-11ea-92ed-5615559fbcc1.png)
Push all content within content section, current design is too stretched out. Content section is 928 px at the center for 1440 px screen, 328 px for 360 px screen 

![image](https://user-images.githubusercontent.com/5694308/79294577-b9abe800-7f00-11ea-9886-a8e9d9a49be0.png)

**Comment by paulchrisluke** [comment]
One last, minor thing 
![image](https://user-images.githubusercontent.com/5694308/79410204-f263c400-7fc9-11ea-926b-7528a6542256.png)
missed this the first time, sorry

Text Style: 
```
/* Mobile Body 1 */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 20px;
/* identical to box height, or 125% */
```

**Comment by mort3za** [comment]
> Back button should be this text style below

Pushed a commit to master.
