### ISSUE TITLE
Settings - Settings Page

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corperate-communications#40]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

For the design and the flow, go to the "Prototype" page. For the smart suggestion warnings/article prioritization/layout, see "Logic Map" page.

This milestone is due **April 6th, 2020**

Your mission, should you accept, includes these tasks: 

- [x] 1. [Top Navigation ](#top-navigation) #25 
- [x] 2. [Expansion Panel](#expansion-panel) 

![image](https://user-images.githubusercontent.com/5694308/78641485-81daea00-78db-11ea-9d12-0377b5673fe8.png)

<h1 id="top-navigation">1. Top Navigation</h1> 

![image](https://user-images.githubusercontent.com/5694308/78631985-0459ae80-78c8-11ea-8c52-7120f6054700.png)

This is the same as #25 WITHOUT the stepper navigation section and the text action 
Title: Settings
Back Icon: Dashboard #41

<h1 id="expansion-panel">2. Expansion Panel</h1> 

![image](https://user-images.githubusercontent.com/5694308/78632050-2eab6c00-78c8-11ea-8c95-e2008f61188f.png)

## Content 
Setting Option: Email Campaign (leads to #42 )

## Text Style
Setting Option: 
```
/* Body 1 */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 20px;
/* identical to box height, or 125% */
```

## Color 
Icon: On Background Medium Emphasis (#000000, 54%)
Setting Option: On Background High Emphasis (#000000, 84%) 
Divider: On Background Divider (#000000, 12%)

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/79437029-d416bc00-7ffb-11ea-91cf-c2e267d0edb6.png)

We've added a new item to our settings page: "Memo Activity" 
Styling is identiccal to "email campaign" above, and links to #76

**Comment by linuxuser07** [comment]
I'll be working on this

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/79861463-a3b98e00-83fe-11ea-9e00-029303e44f1c.png)

![image0](https://user-images.githubusercontent.com/5694308/79862007-905af280-83ff-11ea-9933-f084d76aae2a.png)

It looks like there is a shadow below "log in" 
That should be a 1 pixel divider in the color "On Background, Divider (#000000, 12%) 

![image](https://user-images.githubusercontent.com/5694308/79862123-cbf5bc80-83ff-11ea-893b-04040dce3d23.png)

Also, we have modified the "Log In" color in our designs to be the "Error" color (#FF5959)

**Comment by mort3za** [comment]
kinda duplicate of https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/issues/93
