### ISSUE TITLE
Log In Page

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corperate-communications#69]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

This is the log in page for Volkswagen's CMS 
![image](https://user-images.githubusercontent.com/5694308/79426504-6ebbce80-7fed-11ea-8ac7-0935303f1e27.png)

# Content   
**Title:** Welcome to Jumpstart 
**Text Fields:** 
Field 1 Label: Email
Field 2 label: Password 
**Button:** Log In (leads directly to memo flow #62 )
**Text hyperlink:** Forgot Password (Leads to Password Reset #70 ) 

# Asset 
![Volkswagen_logo_2019 1](https://user-images.githubusercontent.com/5694308/79414531-14af0f00-7fd5-11ea-86cc-39cfcda1c5fd.png)
https://user-images.githubusercontent.com/5694308/79414531-14af0f00-7fd5-11ea-86cc-39cfcda1c5fd.png

# Text Style 
Title: 
```
/* Mobile H1 */

font-family: Work Sans;
font-style: normal;
font-weight: bold;
font-size: 32px;
line-height: 38px;
```

Text Field Label, Input: 
```
/* Mobile Body 1 */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 20px;
/* identical to box height, or 125% */
```

Color Label:
```
/* Color Label */

font-family: Work Sans;
font-style: normal;
font-weight: 500;
font-size: 14px;
line-height: 24px;
/* identical to box height, or 171% */

letter-spacing: 0.02em;
text-transform: uppercase;
```

Text: 
```
/* Caption */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
/* identical to box height, or 133% */
```

# Color 
**Background:** 
```
/* Blue Gradient Background */

background: radial-gradient(50% 49.2% at 0% 0.8%, rgba(255, 255, 255, 0.25) 0%, rgba(255, 255, 255, 0) 100%), #011D51;
```

**Title:** On Primary High Emphasis (#FFFFFF, 84%) 

**Text Field:**
Label, Border: On Primary, Disabled (#FFFFFF, 38%) 
Input Text: On Primary High Emphasis (#FFFFFF, 84%) 

**Button:**
Background; Secondary (#03B3F9)
Text: On Secondary, High Emphasis (#FFFFFF, 84%)

**Text Hyperlink:** On Primary, Medium Emphasis (#FFFFFF, 54%)

**Comment by mort3za** [comment]
@paulchrisluke This is dashboard page that shows a login form, right?  
What's there if user was logged in?

**Comment by mort3za** [comment]
Nevermind, found answer on figma

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/79547971-edcd0780-80be-11ea-9e2b-eedeec7f5528.png)
When information is inputted using autofill, text field colors are not correct 

![image](https://user-images.githubusercontent.com/5694308/79548132-27057780-80bf-11ea-82e5-d6c14154870b.png)
Normal input colors are fine
