### ISSUE TITLE
Setting - Import Email List Page

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corperate-communications#74]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

For the design and the flow, go to the "Prototype" page. For the smart suggestion warnings/article prioritization/layout, see "Logic Map" page.

This milestone is due **April 6th, 2020**

Your mission, should you accept, includes these tasks: 

- [x] 1. [Top Navigation ](#top-navigation) #25 
- [x] 2. [File Instructions](#instructions) 
- [x] 3. [Upload Process](#upload)
- [x] 4. [Style Upload Form](#upload)

![Add Email List](https://user-images.githubusercontent.com/5694308/79422973-01f20580-7fe8-11ea-8768-03717b843ea9.png)

<h1 id="top-navigation">1. Top Navigation</h1> 

![image](https://user-images.githubusercontent.com/5694308/79422868-d40cc100-7fe7-11ea-8080-28855615b634.png)

## Content
This is similar to #25 EXCEPT 
1. no stepper navigation section
2. No Text Action 

Title: 
Back Icon: Leads to #43 Email Lists

## Asset
https://res.cloudinary.com/whynotearth/image/upload/v1587102533/Volkswagen/cms/back_oay5wt.png 

<h1 id="instructions">2. Email List Instructions</h1> 

![image](https://user-images.githubusercontent.com/5694308/79423211-6745f680-7fe8-11ea-9182-cf6e217bad79.png)

## Content 
Text:
To prepare your file for import, follow these steps: 
1. In a spreadsheet program like Excel or Google Sheets, open your blank worksheet.
2. Create and label a column for **Email Address**.
3. Next to your Email Address column, create and label additional columns for **First Name** and **Last Name**.
Email address is the only field that we require, but you can repeat this step for any other contact data fields you want to included. 
4. Paste your contacts’ information into the relevant fields in the spreadsheet. 
5. Save the file in CSV format. This option can usually be access from the File menu in your spreadsheet program, labeled as “Export as .CSV” or “Download as .CSV" 

## Asset 

![image 11](https://user-images.githubusercontent.com/5694308/79423285-89d80f80-7fe8-11ea-92dc-c7c3a70e985b.png)
![image 12](https://user-images.githubusercontent.com/5694308/79423287-8b093c80-7fe8-11ea-858b-8aceab4aa6ab.png)
![image 13](https://user-images.githubusercontent.com/5694308/79423288-8ba1d300-7fe8-11ea-8ca6-23eeebeff8d7.png)

## Text Style
Text: 
```
/* Mobile Body 1 */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 20px;
/* identical to box height, or 125% */
```

Bolded Text: 
```
/* Body 1 Emphasis */

font-family: Work Sans;
font-style: normal;
font-weight: 600;
font-size: 16px;
line-height: 20px;
/* identical to box height, or 125% */
```

## Color 
Text: On Background High Emphasis (#000000, 84%) 

<h1 id="upload">3. Upload process</h1> 

![image](https://user-images.githubusercontent.com/5694308/79423502-f05d2d80-7fe8-11ea-985e-ec3d7ca5bf89.png)
Image shows default on left, and the right side shows uploaded file. 

##  Content 
Expansion panel title: Upload 
File Preview: {{ Uploaded File Name (only shows after file added) }} 
Add Icon: (Press to prompt upload process from device) 
Button text: Upload File (Upload Selected File, move to success #28, automatically move to display new list in it's own #44 Email List Page )

## Asset 
![add](https://user-images.githubusercontent.com/5694308/79423812-71b4c000-7fe9-11ea-930d-46c0de6605b9.png)

## Color 
Background: Background (#FFFFFF) 
Divider: On Background Divider (#000000, 12%) 
File Preview: On Background Medium Emphasis (#000000, 54%) 
Button Background: Primary (#011D51)
Button Text: On Primary High Emphasis (#FFFFFF, 84%) 

## Text Style 
Expansion panel title, File Preview
```
/* Mobile Body 1 */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 20px;
/* identical to box height, or 125% */
```

## Shadow 
Button Shadow
```
/* 2 dp */

background: #C4C4C4;
box-shadow: 0px 1px 5px rgba(0, 0, 0, 0.2), 0px 3px 4px rgba(0, 0, 0, 0.12), 0px 2px 4px rgba(0, 0, 0, 0.14);
```

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/79715226-5275a580-82fd-11ea-9ac7-502501ab5089.png)

This is the same upload component as vuetify outline field 

https://vuetifyjs.com/en/components/file-inputs/


# Content
Upload Field Label: Upload File 
Chip Text: {{ File Name }} 

# Asset 
![AttachmentIcon](https://user-images.githubusercontent.com/5694308/79715238-65887580-82fd-11ea-8513-dda9ffda7d06.png)

![icon remove](https://user-images.githubusercontent.com/5694308/79715424-e182bd80-82fd-11ea-9abb-c73d3038fb47.png)

# Text Style
```
/* Mobile Body 1 */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 20px;
/* identical to box height, or 125% */
```

Floating Label, Chip Text:
```
/* Mobile Caption */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
/* identical to box height, or 133% */
```

# Color
Upload Field: On Background, Disabled (#000000, 38%) 
Chip Border: On Background Divider (#000000, 12%)
Chip Text: On Background, High (#000000, 84%)

**Comment by sally** [comment]
I mentioned this in [PR #27](https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/pull/27) but I'll be holding off on working on this until more of the dependent work on Settings pages are merged so that it's easier for me to build/expand on the foundations
