### ISSUE TITLE
Temp Dashboard Page

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corperate-communications#75]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

This is the temporary dashboard for Volkswagen's CMS 
![image](https://user-images.githubusercontent.com/5694308/79427988-bba0a480-7fef-11ea-96d8-7f9b5d45ac5d.png)

# Content   
**Title:** Welcome to Jumpstart 
**Button:** New Memo (leads directly to memo flow #62 )
**Settings Icon:** (Leads to #40 Settings page)

# Asset 
VW Logo
![Volkswagen_logo_2019 1](https://user-images.githubusercontent.com/5694308/79414531-14af0f00-7fd5-11ea-86cc-39cfcda1c5fd.png)
https://user-images.githubusercontent.com/5694308/79414531-14af0f00-7fd5-11ea-86cc-39cfcda1c5fd.png

Wheel Icon
![wheel 2](https://user-images.githubusercontent.com/5694308/79428146-ef7bca00-7fef-11ea-910e-ba0b41194845.png)
https://user-images.githubusercontent.com/5694308/79428146-ef7bca00-7fef-11ea-910e-ba0b41194845.png

# Text Style 
Title: 
```
/* Mobile H1 */

font-family: Work Sans;
font-style: normal;
font-weight: bold;
font-size: 32px;
line-height: 38px;
```

Button Text:
```
/* Color Label */

font-family: Work Sans;
font-style: normal;
font-weight: 500;
font-size: 14px;
line-height: 24px;
/* identical to box height, or 171% */

letter-spacing: 0.02em;
text-transform: uppercase;
```

Text: 
```
/* Caption */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
/* identical to box height, or 133% */
```

# Color 
**Background:** 
```
/* Blue Gradient Background */

background: radial-gradient(50% 49.2% at 0% 0.8%, rgba(255, 255, 255, 0.25) 0%, rgba(255, 255, 255, 0) 100%), #011D51;
```

**Button:**
Background; Secondary (#03B3F9)
Text: On Secondary, High Emphasis (#FFFFFF, 84%)

# Animation
On tapping the "log in" button of the log in page, email and password dissapears, button slides up into position in the page and button text changes into "new memo". Settings icon appear

**Comment by mort3za** [comment]
- [ ] link to add memo
- [ ] logo and login form
- [ ] animations

**Comment by paulchrisluke** [comment]
@mort3za 
We are actually moving log out to the settings menu
![image](https://user-images.githubusercontent.com/5694308/79550201-3639f480-80c2-11ea-8d94-acf76478d099.png)
Instead of the log in, this should be the settings icon (asset above), we need the settings menu for file import flow as well
