### ISSUE TITLE
Memo Form - Distribution List Search

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corperate-communications#85]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

Your mission, should you choose to accept: 
We added a new text field to our memo form: "To:". Similar to Gmail, our Memo form #62 should suggest a distribution list as you are typing in to the text field through a drop down menu. Upon selection, it appears as a chip 
![gif](https://i.gyazo.com/e63b14437bffe2e95963ae910c12d124.gif)

New Parts: 
- [x] 1. [Text Field](#text-field)
- [x] 2. [Drop Down Menu](#drop-down-menu)
- [x] 3. [Chips](#chips)
- [ ] 4. [Animation](#animation)

<h1 id="text-field">1. Text Field</h1> 

The new text field is identical in styling to the existing text fields on the memo form page #62 
![image](https://user-images.githubusercontent.com/5694308/79628109-51f7d600-8168-11ea-916c-e07d8c338b44.png)

## Content
**Label:** To: 

<h1 id="drop-down-menu">2. Drop Down Menu</h1> 

![image](https://user-images.githubusercontent.com/5694308/79628127-81a6de00-8168-11ea-99e5-9dffa07b4c9f.png)
![image](https://user-images.githubusercontent.com/5694308/79628128-853a6500-8168-11ea-91f9-be6dc8986075.png)

## Content
The drop down menu displays all options as users are typing

Users should be able to search both distribution lists and individual emails within the distribution lists, but lists are placed at a higher priority than individual emails on the drop down menu itself 

## Text Style 
Search Results: 
```
/* Mobile Body 1 */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 20px;
/* identical to box height, or 125% */
```

## Color
Surface: Surface (#FFFFFF) 
Search Results: On Surface, High Emphasis (#000000, 84%) 
Hover Highlight: Secondary, Divider (#03B3F9, 12%)

## Shadow
```
/* 8 dp */

background: #C4C4C4;
box-shadow: 0px 4px 5px rgba(0, 0, 0, 0.2), 0px 3px 14px rgba(0, 0, 0, 0.12), 0px 8px 10px rgba(0, 0, 0, 0.14);
```

<h1 id="chips">3. Chips</h1> 

![image](https://user-images.githubusercontent.com/5694308/79628254-9637a600-8169-11ea-8b60-ee01f0683d7c.png)

## Content
Text: {{ Chosen Distribution list or email }} 

## Text Style 
Text: 
```
/* Mobile Caption */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
/* identical to box height, or 133% */
```

## Colors
Chip Background: Surface
Text: On Surface, High Emphasis (#000000, 84%)

## Asset 
![icon remove](https://user-images.githubusercontent.com/5694308/79628383-ae5bf500-816a-11ea-86ec-39c0a0b3cc8b.png)

## Animation 
https://material.io/components/chips#input-chips See "Input Chip Behavior" 

<h1 id="animation">4. Animation</h1> 

![gif](https://i.gyazo.com/e63b14437bffe2e95963ae910c12d124.gif)

As users type, drop down menu appears to show search options. Upon tapping, text turns into a chip with the selected drop down menu item

**Comment by mort3za** [comment]
- [ ] Add error validation
- [ ] Test on staging API

**Comment by paulchrisluke** [comment]
# Input Field 
![image](https://user-images.githubusercontent.com/5694308/79738761-633b1100-8327-11ea-809e-919b5d5ff2ea.png) Current "To:" section
![image](https://user-images.githubusercontent.com/5694308/79738785-6df5a600-8327-11ea-86fe-e63eb40f6330.png) Example Text Field 

The "To:" needs to look identical to our text field, like in our designs 
![image](https://user-images.githubusercontent.com/5694308/79739087-e197b300-8327-11ea-8119-0e5b53b05850.png)

# Drop Down Menu
![image](https://user-images.githubusercontent.com/5694308/79739591-97630180-8328-11ea-8db6-77bf1d1f6161.png)
The current "drop down menu" is a bullet list that pushes down the other content 
![gif](https://i.gyazo.com/31714a492fdeeeb426c10215d59a8322.gif)

We need a drop down menu within a card that floats above the other content of the page 
![gif](https://i.gyazo.com/10a8ee7b728ff2db13d9781666a5ecc8.gif)
this gif is an example of how if we hide the menu the other text field just appears under the menu layer and and doesn't get pushed down 

# Chips 
![image](https://user-images.githubusercontent.com/5694308/79739478-6e427100-8328-11ea-8a05-255b9dc4db2a.png)
![image](https://user-images.githubusercontent.com/5694308/79742175-a21f9580-832c-11ea-9117-f30b8371db25.png)

Currently, the above image is what happens when you add a "chip". There are no visual options to deleted the "chip" and it doesnt have the border around it. There's a weird cutoff on the text as well 

We need to have the visual of the chips added as well 
![image](https://user-images.githubusercontent.com/5694308/79739537-83b79b00-8328-11ea-9057-7b4924f8fee8.png)

There is also an issue with multiple "chips", where it start a new line of "To:" 
![image](https://user-images.githubusercontent.com/5694308/79741691-e2cadf00-832b-11ea-9f65-7a70e6260ac9.png)

**Comment by paulchrisluke** [comment]
https://deploy-preview-28--vw-email-cms.netlify.app/
This is on chrome incognito and edge inprivate, edge 81, Firefox

![gif](https://i.gyazo.com/f47f55736efefeecc1229dc45eb044ea.gif)
This is what the current "To:" field looks like, where if there is an existing chip, it pushes content down to add another empty row below with a new "To:". There's also an odd drop down shadow that shows up 

![gif](https://i.gyazo.com/006bd84ab438ef763cc78f50f071e349.gif)
The behavior should be more similar to gmail, where users can continue typing inline (no extra "To:"  or new line) to add more lists to the memo 


Also, change the color of the x from this green to our primary color (#011D51)
![image](https://user-images.githubusercontent.com/5694308/79820731-23bc0580-83b7-11ea-8bd4-d0af4939fdab.png)

![image](https://user-images.githubusercontent.com/5694308/79821972-48fe4300-83ba-11ea-9efb-5e6bd1a596eb.png)
On Safari (iOS, Mac), the potential email lists cannot be displayed or searched

**Comment by paulchrisluke** [comment]
![gif](https://i.gyazo.com/e788bf757ee9f5ad3fb6ac88ab649b10.gif)
When a chip is already added, and you can start typing another one, there is a small, empty drop down that appears below
Drop down should only appear if user has typed something into the field after. If they haven't, do not show empty drop down card

Microsoft edge 81 inprivate, iphone X safari private/chrome/chrome private, Safari Mac Mojave

**Comment by mort3za** [comment]
@paulchrisluke please don't move to done before merging :D
