### ISSUE TITLE
improve shadows on blue delta email

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corperate-communications#89]
we need to improve our shadows no the blue delta email to be truer to our design. We designed a way to cheat these shadows with multiple grey layers, but feesability may be hard here. I know Mort3za was thinking there may be another way to do this.

https://www.figma.com/file/IfThqYyXXm8HZ7AAS7zhbF/Cheating-Shadows?node-id=0%3A1

goal:

![A4 - 7 Draft 69](https://user-images.githubusercontent.com/5694308/80986374-af736e80-8e5a-11ea-8e5f-031cd0ff61c8.png)

# I think the solution may be to use absolute positioning for our outlook email and positining the grey boxes behind the dynamic text boxes absolutely.

https://stackoverflow.com/questions/36228161/using-text-shadow-in-html-email-with-inline-css

- [x] Shadow for priority article
- [x] Shadow for middle articles
- [x] Shadow for bottom article

**Comment by paulchrisluke** [comment]
I think the solution may be to use absolute positioning for our outlook email and positining the grey boxes behind the dynamic text boxes absolutely.

https://stackoverflow.com/questions/36228161/using-text-shadow-in-html-email-with-inline-css

**Comment by paulchrisluke** [comment]
![image0 (16)](https://user-images.githubusercontent.com/5694308/82212363-a1cee600-993c-11ea-8965-11ef14023086.png)
Our email article shadows currently looks like this, with the shadows tending toward the right 

The shadow should look something more similar to this (Exaggerated in image for clarity): 
![image](https://user-images.githubusercontent.com/5694308/82212905-7ef10180-993d-11ea-95fa-0c9045f97a38.png)

Where the shadow is centered, with slightly more sticking out below than left or right
Left and right side shadow should be equal

**Comment by mort3za** [comment]
[dist.zip](https://github.com/whynotearth/Volkswagen-email-corperate-communications/files/4652231/dist.zip)

@ctyar minor styling update.

![image](https://user-images.githubusercontent.com/510242/82359771-999aa780-9a1d-11ea-910c-57de0f4f9444.png)

@bamboochow preview link: https://app.emailonacid.com/app/acidtest/0ve4qGfph5jDN6xJJ3khog6BwnczRRB22kZIFw8QrfjjC/list
