### ISSUE TITLE
Create Tablet Email Template

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corperate-communications#9]
This is the tablet email template for Volkswagen 
![image](https://user-images.githubusercontent.com/5694308/76948966-6d3dae80-693a-11ea-93a0-cffc1c6b85e4.png)
![image](https://user-images.githubusercontent.com/5694308/76949064-952d1200-693a-11ea-998c-e6a9272639be.png)

### Tablet Template 

The length of each article is dependent on the content. This template has 3 basic parts:
1. Header
2. Content 
3. Footer 

#### 1. Header
The header includes the newsletter title and the date. The title is 24 pixels from the top, centered.
![image](https://user-images.githubusercontent.com/5694308/76948437-ac1f3480-6939-11ea-9006-d069340a90cc.png)
The header includes the newsletter title and the date. The title is 24 pixels from the top, centered.

**Title** 
The title is centered and is 24 pixel away from the top
Font: Display 3
Color: Primary 

**Date** 
The date is centered horizontally in the device screen and vertically with the dividers. 
Font: Caption
Color: On Background 
Emphasis: High 

**Dividers** 
The dividers start from both ends and end 8 pixels away from the date, which is centered horizontally in the device screen and vertically with the dividers.
Color: On Background 
Emphasis: Divider 

#### 2. Content 
The content is just a list of category cards #6 in tablet sizing that are 40 pixels away from each other, and 32 pixels from the edge of the screen left and right. 
![image](https://user-images.githubusercontent.com/5694308/76949363-02d93e00-693b-11ea-9eb5-75025e115c1c.png)

#### 3. Footer
The footer is a full-width color bar with icons at the center. The icons are 32 pixels away from each other, centered. 
![image](https://user-images.githubusercontent.com/5694308/76945610-58125100-6935-11ea-81d6-67812537e633.png)

**Icons**
The icons are 24 x 24 pixels 
Color: On Primary 
Emphasis: Medium 

**Background**
The background extends 24 pixels above and below the icons. 
Color: Primary 

### Design File
The specs for the component can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637

**Comment by mort3za** [comment]
We have only one breakpoint in emails, usually near 600px. So I assume the tablet is the same as desktop

**Comment by mort3za** [comment]
What that share icon do exactly? If that opens mobile sharing menu, it's only available outside of email inbox, on browsers because we don't have JavaScript.

**Comment by paulchrisluke** [comment]
Remove the share button

**Comment by paulchrisluke** [comment]
This is the same issue in the comment for #10 

This is seen in windows, outlook app
![image](https://user-images.githubusercontent.com/5694308/79301612-3a281400-7f14-11ea-98ea-b640ef36bf62.png)
improper alignment of titles and an extra, large answers at a glance title 
 
There is a weird cut out for answers at a glance, and the gray area cuts out early 
![image](https://user-images.githubusercontent.com/5694308/79301649-4ca24d80-7f14-11ea-9f55-79da17833a13.png)

Some outlook versions have this misalignment in the tabs 
![image](https://user-images.githubusercontent.com/5694308/79302083-7dcf4d80-7f15-11ea-8509-07fcde23c312.png)

Other tests generated from this link 
https://app.emailonacid.com/app/acidtest/k9hvypmkSia9TaO8F46HSi0EHjffDsncAVxoslqWK34Vv/list
Seems like other outlook ones have early cutoff of the gray area of answers at a glance 

Outlook 2010, 2013, 2016, 2019 all have this alignment/cut off issue
