### ISSUE TITLE
Email Template Inconsistent Border Thickness 

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corperate-communications#90]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

For the template design, go to the "Current Email Template Designs" page. This issue is for the blue delta email template 

# Border Thickness 
There is an inconsistency between different posts of the same category in our email 
![image1 (6)](https://user-images.githubusercontent.com/5694308/80961120-732d1780-8e34-11ea-99ad-132ac7cc5848.png)
![image0 (13)](https://user-images.githubusercontent.com/5694308/80961123-745e4480-8e34-11ea-90a2-0daaf9b3ccc8.png)
One of these Plant category components have a thicker border line. 

![image](https://user-images.githubusercontent.com/5694308/80961167-8c35c880-8e34-11ea-9f49-23c2a5d224c2.png)
In our designs, the only category that should have a thicker border is Priority. Any other categories should have a 1 px border

**Comment by mort3za** [comment]
It was probably a data injection problem. Should be fixed in new version.
