### ISSUE TITLE
3 column template page

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corperate-communications#93]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

For the design and the flow, go to the "Current Email Template Designs" page. 

# 3 Column Template Page 
We need a 5 article page email template without the answers at a glance module 
![image](https://user-images.githubusercontent.com/5694308/80936044-a2726300-8df9-11ea-8ce0-0ceae6bd97f4.png)

There should be space for 5 articles that are not the answers at a glance component, with two horizontal sections at the top and 3 smaller sections in the middle 

This is used in the [email drafting flow](https://github.com/whynotearth/Volkswagen-email-corperate-communications/issues/27) for the email preview as users select articles for a new email 

Completed email templates are also displayed on the dashboard whynotearth/Volkswagen-email-corporate-communications-CMS#120

**Comment by mort3za** [comment]
This is not something we could do in one day. But will be in my priority list as it is in todo list.

**Comment by paulchrisluke** [comment]
Ui is looking good, waiting for test emails to be sent out

**Comment by mort3za** [comment]
This is the Emailonacid preview link https://app.emailonacid.com/app/acidtest/m18pboy8oZGS2jL8Mg6lYapW15yiexihaRoEU0FqLGaSe/list

**Comment by paulchrisluke** [comment]
print version should show this as well (not a tonight thing)

**Comment by mort3za** [comment]
> print version should show this as well (not a tonight thing)

@paulchrisluke seems working, I received an email today, print version had 3 column version too.
